OPSST-103: Add ARCUST file generation
StennGroup/portfolio-reports-service pull request #3
Opened 2022-10-11 10:44 UTC by ignat-kalinich-stenn

2022-10-17 14:17 UTC, iagur-aleksei-stenn approved these changes

2022-10-17 14:17 UTC, iagur-aleksei-stenn commented on src/PortfolioReportsService.UnitTests/IntegrationTests/OperationsApiTests.cs
> +[Explicit("Run only to ensure contract with your eyes")]
Может быть не "to ensure", а "to check"?

2022-10-17 14:17 UTC, iagur-aleksei-stenn commented on src/PortfolioReportsService.UnitTests/UnitTests/CustomerFileGenerationTests.cs
> +    public void FileGeneratedWithOneCustomerPair()
Давай придерживаться общего подхода в именовании тестов - НазваниеТестируемогоМетода_Условия_Результат. Пример: https://github.com/StennGroup/stenn.sage-adapter/blob/prod/src/SageIntegration.Tests/Infrastructure/Repay/RepayInvoiceActionSdfTests.cs#L24

Плюс, разделять тесты комментариями на arrange, act, assert части. Пример в том же файле можешь увидеть.

2022-10-17 14:18 UTC, iagur-aleksei-stenn requested changes
Два комментария добавил

2022-10-17 14:27 UTC, ignat-kalinich-stenn commented on src/PortfolioReportsService.UnitTests/UnitTests/CustomerFileGenerationTests.cs
> +    public void FileGeneratedWithOneCustomerPair()
Названия тестов поменял. На arrange, act, assert разделил позже, когда делал OPSST-104

2022-10-17 14:28 UTC, ignat-kalinich-stenn commented on src/PortfolioReportsService.UnitTests/IntegrationTests/OperationsApiTests.cs
> +[Explicit("Run only to ensure contract with your eyes")]
Done

2022-10-18 12:56 UTC, iagur-aleksei-stenn approved these changes

2022-10-19 06:05 UTC, merged